# Generated by Django 4.2 on 2023-04-14 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('social_media_link', models.URLField(blank=True)),
                ('website_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Найчастіші запитання', 'Найчастіші запитання'), ('Питання щодо навчання', 'Питання щодо навчання'), ('Фінанси', 'Фінанси'), ('Приймальна комісія', 'Приймальна комісія')], max_length=50)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_answer.faculty')),
            ],
        ),
    ]
